### ISSUE TITLE
Authentication Failed - What next, and how to start VideoCalls?

### ISSUE THREAD

**Issue by stephanoparaskeva** [wazo-platform/wazo-react-native-demo#13]
So I have followed the steps on the [guide](https://wazo-platform.org/uc-doc/installation/install-system) and I have the engine running with a user:

<img width="1261" alt="Screenshot 2020-06-23 at 03 51 39" src="https://user-images.githubusercontent.com/40718272/85355651-06193280-b505-11ea-9d07-55a561854f22.png">

And the app running

<img width="394" alt="Screenshot 2020-06-23 at 03 47 56" src="https://user-images.githubusercontent.com/40718272/85355467-93a85280-b504-11ea-9da4-9d63efe92dc4.png">

#### It keeps saying 'Authentication Failed'

I'm using *https:// amazonaddress.compute.amazonaws.com*
How does one then allow users to create audio webrtc chats? what next?

**Comment by stephanoparaskeva** [comment]
@manuquentin Any help if you don't mind?

**Comment by manuquentin** [comment]
Hi @stephanoparaskeva 

I think the best way to discuss this issue related to your installation and not this project is the [Wazo's forum](https://wazo-platform.discourse.group/).

Meanwhile, you can turn on the debugger (using something like React Native Debugger) with the Network inspect turned on and check the XHR section of the Network tab where you'll have a better explanation of your issue.

**Comment by stephanoparaskeva** [comment]
> Hi @stephanoparaskeva
> 
> I think the best way to discuss this issue related to your installation and not this project is the [Wazo's forum](https://wazo-platform.discourse.group/).
> 
> Meanwhile, you can turn on the debugger (using something like React Native Debugger) with the Network inspect turned on and check the XHR section of the Network tab where you'll have a better explanation of your issue.
Ever since downloading wazo-react-native-demo I cannot see any network requests in the demo, and I can no longer see network requests in my actual app (after converting it using the demo)
<img width="1153" alt="Screenshot 2020-06-23 at 14 46 45" src="https://user-images.githubusercontent.com/40718272/85411672-8a4cd380-b560-11ea-84d5-1dbca9ed1582.png">
<img width="1071" alt="Screenshot 2020-06-23 at 14 47 21" src="https://user-images.githubusercontent.com/40718272/85411676-8b7e0080-b560-11ea-9272-a5b8761c0b32.png">




I've been debugging all day and I see no request in network tab, I provided the server as:
https://ec2-xyz123.eu-west-1.comput.amazonaws.com

I coukd post in the forum but surely there is a step I have missed, It seems to be a problem with the wazo-demo and not something else. It just hangs at the request. Using axios I get no error for axios.get(https://google.com) but I get an error for axios.get(`https://wazoawsdns.compute.amazonaws.com`) I get nothing just throws an error:

I I do `http https://awswazo.comput.amazonaws.com` I get
SLError: HTTPSConnectionPool(host='.eu-west-1.compute.amazonaws.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1108)'))) while doing a GET request to URL: https://ec2-

i simply installed the engine onto aws, deleted apache2, changed index.html to index.html.old following this guide https://www.youtube.com/watch?v=p54PdJ18KXM And started server.
I went to like and added users which worked great.

Then downloaded wazo-react-native-demo put in credentials and server and it just hangs then says 'Authentication Failed' I don't see any network requests in RN Debugger and so I think it is an issue with the demo

The request just hangs on demo. And my app is now the same.

Now I've lost network debugging in my app and aud/video calling doesnt work... I've tried everything and spent a lot of time.

**Comment by manuquentin** [comment]
You have to enable it with a right click in the tabs:
<img width="226" alt="Screen Shot 2020-06-23 at 9 53 55 AM" src="https://user-images.githubusercontent.com/2076632/85412412-8bb5d600-b537-11ea-92e8-529ecb9c9af4.png">

I think it's an issue with your SSL certificat. As a temporary workaround, you can maybe accept it by typing your engine URL in your mobile browser and accept the self signed certificate.

But in the wazo's forum you'll have you answer.

**Comment by stephanoparaskeva** [comment]
I will post in the forums but they are very slow, is there any way you can give me some ideas so I am not completely on my own with this one?

I've tried accepting it by entering engine URL
But no luck, it just hangs then fails:
<img width="380" alt="Screenshot 2020-06-23 at 15 02 03" src="https://user-images.githubusercontent.com/40718272/85413478-c5e89d00-b562-11ea-9085-b119c49f1b9e.png">

<img width="380" alt="Screenshot 2020-06-23 at 15 01 37" src="https://user-images.githubusercontent.com/40718272/85413433-ba957180-b562-11ea-9a24-eb34d2da46b8.png">

<img width="380" alt="Screenshot 2020-06-23 at 15 03 14" src="https://user-images.githubusercontent.com/40718272/85413443-bd906200-b562-11ea-81d3-081d89723f4b.png">

**Comment by manuquentin** [comment]
And what about the XHR request after enabling the Network inspection in the debugger ?

**Comment by stephanoparaskeva** [comment]
> And what about the XHR request after enabling the Network inspection in the debugger ?

I havent been able to locate what you're suggesting, you mentioned to Right Click on tabs but I cant find the options

**Comment by stephanoparaskeva** [comment]
> And what about the XHR request after enabling the Network inspection in the debugger ?

Ah I've found it! This is what I'm seeing
<img width="461" alt="Screenshot 2020-06-23 at 15 24 17" src="https://user-images.githubusercontent.com/40718272/85415812-aa32c600-b565-11ea-85c5-0d413c90ce7d.png">

**Comment by manuquentin** [comment]
Ok now what's the content returned by this call ?

**Comment by stephanoparaskeva** [comment]
> Ok now what's the content returned by this call ?

It says `Failed to Load Response Data`
<img width="305" alt="Screenshot 2020-06-23 at 15 26 10" src="https://user-images.githubusercontent.com/40718272/85416029-eb2ada80-b565-11ea-84c4-01085dd095c2.png">

After it times out it just turns red

**Comment by stephanoparaskeva** [comment]
This is the request in browser
<img width="825" alt="Screenshot 2020-06-23 at 15 28 15" src="https://user-images.githubusercontent.com/40718272/85416345-41981900-b566-11ea-8a24-d7229275f2f5.png">

**Comment by manuquentin** [comment]
It seems it's due to a bad ssl certificate. 
You'll have you answer in the forum. This is not the place to discuss the issue.

**Comment by stephanoparaskeva** [comment]
> It seems it's due to a bad ssl certificate.
> You'll have you answer in the forum. This is not the place to discuss the issue.

I've posted my issue in the forums here If you can let someone know or help me yourself! I'd really like to work with Wazo if I can :D
https://wazo-platform.discourse.group/t/i-think-i-have-a-bad-ssl-certificate-and-i-cant-authenticate-a-user-in-wazo-react-native/455
